; Qwen3.6 35B A3B - general tasks (instruct / no thinking)
[qwen3.6-35b-a3b-instruct]
model = /models/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf
; --fit system handles ngl automatically, no manual n-cpu-moe needed
fit = true
fit-target = 300
fit-ctx = 128000
; model config
; Based on Unsloth recommendations https://unsloth.ai/docs/models/qwen3.6
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}
; performance config
; no-mmap = true
; parallel = 1
flash-attn = true
batch-size = 2048
ubatch-size = 2048
cache-type-k = q8_0
cache-type-v = q8_0

; Qwen3.6 35B A3B - precise coding tasks etc (reasoning)
[qwen3.6-35b-a3b-reasoning]
model = /models/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf
; --fit system handles ngl automatically, no manual n-cpu-moe needed
fit = true
fit-target = 300
fit-ctx = 128000
; model config
; Based on Unsloth recommendations https://unsloth.ai/docs/models/qwen3.6
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
; increasing presence-penalty reduces time spent reasoning
; Unsloth recommends 0.0 for coding, but might cause long loops etc 
presence-penalty = 0.5
repeat-penalty = 1.0
reasoning = on
chat-template-kwargs = {"enable_thinking": true, "preserve_thinking": true}
; performance config
; no-mmap = true
; parallel = 1
flash-attn = true
batch-size = 2048
ubatch-size = 2048
cache-type-k = q8_0
cache-type-v = q8_0

